# Generated by Django 3.0 on 2020-01-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('c_first_name', models.CharField(max_length=30)),
                ('c_last_name', models.CharField(max_length=30)),
                ('c_email', models.EmailField(max_length=100)),
                ('c_password', models.CharField(default='password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('m_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('m_movie_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('t_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('t_tickets', models.IntegerField()),
                ('t_theatres', models.CharField(max_length=50)),
                ('t_seat_type', models.CharField(max_length=30)),
                ('t_hall', models.CharField(max_length=50)),
                ('cus_id', models.CharField(max_length=50)),
                ('mov_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('u_email', models.EmailField(max_length=100)),
                ('u_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
