# Generated by Django 3.0 on 2020-01-29 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='mov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.Movies'),
        ),
    ]
