# Generated by Django 3.0 on 2020-01-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0004_auto_20200129_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_email',
            field=models.CharField(max_length=100),
        ),
    ]
